spring.application.name=deusto_hotel_clienbt_proxy

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/deusto_hotel
spring.datasource.username=a
spring.datasource.password=a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.mvc.format.date=iso

server.port=8090